//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ProServiceRemoteProtocol.h"

@class FCPXHost, NSDictionary, NSString, NSViewController;

@interface ProServiceAccessoryPlugin : NSObject <ProServiceRemoteProtocol>
{
    NSDictionary *_hostInfo;
    FCPXHost *_host;
    NSViewController *_viewController;
}

+ (void)startService;
@property(readonly) NSViewController *viewController; // @synthesize viewController=_viewController;
- (void)deliverHostNotification:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
@property(readonly) id <NSObject> host;
@property(readonly) int hostProcessIdentifier;
@property(readonly) NSString *hostBundleIdentifier;
- (id)hostName;
@property(readonly) NSString *hostVersionString;
@property(readonly, nonatomic) NSDictionary *hostInfo;
- (void)loadPlugInSupportFrameworks:(id)arg1 withReply:(CDUnknownBlockType)arg2;
- (void)viewServiceListnerEndPoint:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

